### ISSUE TITLE
Unhandled exeption during open cdp

### ISSUE THREAD

**Issue by Elektron4711** [SilverGreen93/CDPExplorer#6]
I try Version 3.6 as exe-Format.
This comes with different cdp-Files.
Please take a look at this or give me a hint what i can do.

Best Regards
Ralf

![Zwischenablage01](https://user-images.githubusercontent.com/105145650/167286111-17dd7003-754e-4425-9db7-750530d0ea6e.png)

**Comment by SilverGreen93** [comment]
Hi Ralf,

In order to help you, please give me more information such as:
 * the location and file name of your CDP file.
 * Does it contain German characters or other non-ASCII ones?
 * What is the size of the CDP file that you are trying to open?
 * Can you provide a small cdp file that gives you this error to investigate?

Mihai

**Comment by Elektron4711** [comment]
Hi,
i have CDP and exe on my desktop.
No ugly characters.
The size is 16MB.
I habe appended the CDP-File.
Hopefully this will help you to fix it.
This can be a nice Tool. ;-)

PS: I have tested  many CDP-Files and get the same Message.

Ralf

[Bahnhof Mirke.zip](https://github.com/SilverGreen93/CDPExplorer/files/8662924/Bahnhof.Mirke.zip)

**Comment by Elektron4711** [comment]
I solved this.
Start the Explorer as admin AND do not set ReadOnly on the CDP-File.
Maybe you can prevent this in your code.
I like this Tool!

Greetings
Ralf

**Comment by SilverGreen93** [comment]
Fixed with commit [0bd3ba0](https://github.com/SilverGreen93/CDPExplorer/commit/0bd3ba04a35cbcb6a991815ef1beafd9a3df3277)
